insert into role_t values (1, 'ROLE_ADMIN');
insert into role_t values (2, 'ROLE_USER');
insert into configuration_t (config_id, config_name, position, discriminator) values (1, 'positions', 'Bramkarz', 'POSITION');
insert into configuration_t (config_id, config_name, position, discriminator) values (2, 'positions', 'Obrońca',  'POSITION');
insert into configuration_t (config_id, config_name, position, discriminator) values (3, 'positions', 'Pomocnik', 'POSITION');
insert into configuration_t (config_id, config_name, position, discriminator) values (4, 'positions', 'Napastnik', 'POSITION');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (5, 'numbers', 1, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (6, 'numbers', 2, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (7, 'numbers', 3, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (8, 'numbers', 4, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (9, 'numbers', 5, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (10, 'numbers', 6, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (11, 'numbers', 7, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (12, 'numbers', 8, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (13, 'numbers', 9, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (14, 'numbers', 10, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (15, 'numbers', 11, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (16, 'numbers', 12, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (17, 'numbers', 13, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (18, 'numbers', 14, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (19, 'numbers', 15, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (20, 'numbers', 16, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (21, 'numbers', 17, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (22, 'numbers', 18, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (23, 'numbers', 19, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (24, 'numbers', 20, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (25, 'numbers', 21, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (26, 'numbers', 22, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (27, 'numbers', 23, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (28, 'numbers', 24, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (29, 'numbers', 25, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (30, 'numbers', 26, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (31, 'numbers', 27, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (32, 'numbers', 28, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (33, 'numbers', 29, false, 'NUMBER');
insert into configuration_t (config_id, config_name, tshirt_number, is_used, discriminator) values (34, 'numbers', 30, false, 'NUMBER');
